SELECT TOP 1 SORDERQ.SOHNUM_0 
FROM EXPLOIT.SORDERQ AS SORDERQ
WHERE SORDERQ.SOQSTA_0<>3
        AND SORDERQ.SALFCY_0=:facility        
ORDER BY  SO_SHIDATP ASC, SO_SOHNUM ASC, SO_SOPLIN ASC,WO_BOMSEQ ASC, PO_POHNUM ASC, PO_POPLIN ASC 

