SELECT ITMMASTER.ITMREF_0 AS PN,
    AOBJTXT.TYPDOC_0 AS DocType,
	AOBJTXT.CAT_0 AS Cat,
    AOBJTXT.NAM_0 AS Path
FROM AOBJTXT
    LEFT JOIN ITMMASTER
    ON AOBJTXT.IDENT1_0=ITMMASTER.ITMREF_0
-- CAT 5:drawing 9: manuals
WHERE AOBJTXT.ABREV_0='ITM' AND (AOBJTXT.CAT_0=5 OR AOBJTXT.CAT_0=9) AND ITMMASTER.XITM_RACIN_0=:pnRoot