SELECT SORDERP.SALFCY_0 AS FACILITY,
    MIN(DateDiff(day, SORDER.ORDDAT_0,SORDER.SHIDAT_0)) AS MIN,
    AVG(DateDiff(day, SORDER.ORDDAT_0,SORDER.SHIDAT_0)) AS AVG,
    MAX(DateDiff(day, SORDER.ORDDAT_0,SORDER.SHIDAT_0)) AS MAX
FROM SORDERP
    LEFT JOIN SORDER
    ON SORDERP.SOHNUM_0=SORDER.SOHNUM_0
    LEFT JOIN ITMMASTER
    ON SORDERP.ITMREF_0=ITMMASTER.ITMREF_0
WHERE ITMMASTER.XITM_RACIN_0=:pnRoot
    AND DateDiff(day, SORDER.ORDDAT_0,SORDER.SHIDAT_0)<>0
GROUP BY SORDERP.SALFCY_0
