SELECT DISTINCT TOP 50
    XITM_RACIN_0 AS PNROOT,
    ITMREF_0 AS PN
FROM ITMMASTER
WHERE ITMREF_0 LIKE :pnOrPnRoot
    or XITM_RACIN_0 LIKE :pnOrPnRoot
ORDER BY XITM_RACIN_0 DESC, ITMREF_0 DESC