SELECT
    ROWID,
    ITMREF_0 AS PN,
    XITM_RACIN_0 AS PNROOT,
    XITM_IND_0 AS Version,
    YITM_SUP_0 AS WC,
    ITMDES1_0 AS Desc1,
    ITMDES2_0 AS Desc2,
    ITMDES3_0 AS Desc3,
    ITMSTA_0 AS Status,
    CREDAT_0 AS CreateDate
FROM ITMMASTER
WHERE XITM_RACIN_0 = :pnRoot
ORDER BY XITM_IND_0 DESC, YITM_SUP_0 DESC, PN DESC