SELECT
    ROWID,
    ITMREF_0 AS PN,
    XITM_RACIN_0 AS PNROOT,
    XITM_IND_0 AS VER,
    YITM_SUP_0 AS WC,
    ITMDES1_0 AS DES1,
    ITMDES2_0 AS DES2,
    ITMDES3_0 AS DES3,
    ITMSTA_0 AS STATUS,
    CREDAT_0 AS CREATEDATE
FROM ITMMASTER
WHERE XITM_RACIN_0 = 
:pnRoot
ORDER BY VER DESC, PN DESC