SELECT 
    SORDERP.SALFCY_0 AS FACILITY,
    SORDERP.SOHNUM_0 AS SORDER,
    SORDERP.ITMREF_0 AS PN,
    SORDERP.CREDAT_0 AS SDATE,
    SORDERP.NETPRI_0 AS PRICE,
    SORDER.CUR_0 AS CUR
FROM SORDERP
    LEFT JOIN SORDER
    ON SORDERP.SOHNUM_0=SORDER.SOHNUM_0
    LEFT JOIN ITMMASTER
    ON SORDERP.ITMREF_0=ITMMASTER.ITMREF_0
WHERE ITMMASTER.XITM_RACIN_0=:pnRoot 
      AND SORDERP.NETPRI_0 <> 0
ORDER BY SDATE ASC
