SELECT top 100
    SQUOTED.SALFCY_0 AS SalesSite,
    SQUOTED.SQHNUM_0 AS QuoteNO,
    SQUOTED.QUODAT_0 AS QuoteDate,
    SQUOTE.BPCORD_0 AS CustomerCode,
    SQUOTE.BPCNAM_0 AS CustomerName,
    SQUOTED.ITMREF_0 AS PN,
    SQUOTED.QTY_0 AS Qty,
    SQUOTED.NETPRI_0 AS NetPrice,
    SQUOTE.CUR_0 AS Currency,
    SQUOTED.ORDFLG_0 AS OrderFlag,
    SQUOTED.SOHNUM_0 AS OrderNO
FROM SQUOTED
    LEFT JOIN SQUOTE
    ON SQUOTED.SQHNUM_0=SQUOTE.SQHNUM_0
    LEFT JOIN ITMMASTER
    ON SQUOTED.ITMREF_0=ITMMASTER.ITMREF_0
WHERE ITMMASTER.XITM_RACIN_0=:pnRoot
ORDER BY SQUOTED.QUODAT_0 ASC