SELECT
    SORDERP.SALFCY_0 AS SalesSite,
    SORDERP.SOHNUM_0 AS OrderNO,
    SORDER.ORDDAT_0 AS OrderDate,
    SORDER.BPCORD_0 AS CustomerCode,
    SORDER.BPCNAM_0 AS CustomerName,
    SORDERP.ITMREF_0 AS PN,
    SORDERQ.QTY_0 AS Qty,
    SORDERP.NETPRI_0 AS NetPrice,
    SORDER.CUR_0 AS Currency
FROM SORDERP
    INNER JOIN SORDERQ
    ON SORDERQ.SOHNUM_0 = SORDERP.SOHNUM_0
        AND SORDERQ.SOPLIN_0 = SORDERP.SOPLIN_0
    LEFT JOIN SORDER
    ON SORDERP.SOHNUM_0=SORDER.SOHNUM_0
    LEFT JOIN ITMMASTER
    ON SORDERP.ITMREF_0=ITMMASTER.ITMREF_0
WHERE ITMMASTER.XITM_RACIN_0=:pnRoot
    AND SORDERP.NETPRI_0 <> 0
ORDER BY OrderDate ASC
