on:
    workflow_dispatch:
    push:
        tags:
            - 'v*'

# https://github.com/OWNER/REPO/settings/actions
# MUST CHANGE GITHUB_TOKEN PERMISSION FROM READ TO WRITE
# MUST CHANGE GITHUB_TOKEN PERMISSION ALLOW PULL REQUESTS
permissions:
    contents: write
    pull-requests: write

jobs:
    build-and-test:
        strategy:
            matrix:
                os: [ubuntu-latest]
        runs-on: ${{ matrix.os }}
        services:
            postgres:
                image: postgres:13
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_DB: postgres
                ports:
                    - 5432:5432
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Prepare database
              run: PGPASSWORD=postgres psql -h localhost -U postgres -p 5432 -f './src/test/resources/TEST.sql'

            - name: Install JDK
              uses: actions/setup-java@v3
              with:
                  java-version: 17
                  distribution: 'adopt'
                  cache: 'maven'

            - name: Run tests
              run: mvn test

    release-please:
        needs: build-and-test
        strategy:
            matrix:
                os: [ubuntu-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: google-github-actions/release-please-action@v3
              with:
                  release-type: maven
                  #package-name: release-please-action
